### ISSUE TITLE
BusinessCard

### ISSUE THREAD

**Issue by ninanomenon** [overflowerror/NurseBot#1]
As we discussed, I want to expand the BusinessCard class. I noticed that everything was written in the init function. 

Is it okay if I put the different command handlers into different functions?

Since I have done relatively little with java, would it be interesting to know how I clean it the best?

**Comment by sigmasternchen** [comment]
Yes, of course. 

I would suggest you could try to extract the action-lambdas to properties of the class. That way the init method would only contain the adding of the CommandInterpreter-objects but no behavior itself.
